import{S as c,i as a}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const u="44792549-8b3a4a2cfb17648b3cdad98bf",d="https://pixabay.com/api/";function f(o){return o.replaceAll(" ","+"),fetch(`${d}?key=${u}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(t=>{if(t.status!==200)throw new Error(t.statusText);return t.json()}).then(t=>t.hits)}let n=null;function p(){const o=document.querySelector(".gallery");o.innerHTML="",n&&(n.destroy(),n=null)}function m(o){const t=document.querySelector(".gallery"),i=o.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
      <div class="info">
        <p>Likes: ${r.likes}</p>
        <p>Views: ${r.views}</p>
        <p>Comments: ${r.comments}</p>
        <p>Downloads: ${r.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",i),n?n.refresh():n=new c(".gallery a")}function h(){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function y(){document.querySelector(".loader").classList.add("visible")}function g(){document.querySelector(".loader").classList.remove("visible")}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector("#search-form");o.addEventListener("submit",t=>{t.preventDefault();const r=o.querySelector('input[name="searchQuery"]').value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}p(),y(),f(r).then(e=>{e.length===0?h():m(e)}).catch(e=>{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{g()})})});
//# sourceMappingURL=commonHelpers.js.map
