import{S as a,i as c}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const l="44792549-8b3a4a2cfb17648b3cdad98bf",u="https://pixabay.com/api/";function d(r){return fetch(`${u}?key=${l}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true`).then(t=>{if(t.status!==200)throw new Error(t.statusText);return t.json()}).then(t=>t.hits)}function f(){const r=document.querySelector(".gallery");r.innerHTML=""}function m(r){const t=document.querySelector(".gallery"),n=r.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
      <div class="info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",n),new a(".gallery a").refresh()}function p(){c.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function y(){document.querySelector(".loader").classList.add("visible")}function h(){document.querySelector(".loader").classList.remove("visible")}document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector("#search-form");r.addEventListener("submit",async t=>{t.preventDefault();const s=r.querySelector('input[name="searchQuery"]').value.trim();if(!s){iziToast.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}f(),y();try{const e=await d(s);e.length===0?p():m(e)}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}})});
//# sourceMappingURL=commonHelpers.js.map
